#!/usr/bin/env bash

set -x

if ! curl -O https://metacyclopedia.github.io/.astro-indexnow-cache.json; then
    rm .astro-indexnow-cache.json
fi

if [[ -n "$INDEXNOW_KEY" ]]; then
    echo "$INDEXNOW_KEY" >> public/"$INDEXNOW_KEY".txt
fi

astro build

if [[ -f .astro-indexnow-cache.json ]]; then
    cp .astro-indexnow-cache.json dist
fi
